name = "iio"
main = "worker.ts"
compatibility_date = "2025-12-10"

[observability]
enabled = true

[vars]
devenv = 0

[route]
pattern = "api.iio.ie/api/*"
zone_id = "39250e7c6b6397599e85f49b5f0d3bab"

[[kv_namespaces]]
binding = "data"
id = "c72dcb70817340e7b93aa9feeb953e03"
preview_id = "471f1514c6814ecf878693cb6229df81"

[[d1_databases]]
binding = "DB"
database_name = "alogdb"
database_id = "dba8e4d4-fdf5-496b-b1d3-85fc38380579"
